# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesaam < Formula
  desc "Your secret, your rules.
End-to-end encryption and zero-knowledge architecture allows you to share your secret the way you want.
Encrypt your secret and share the secret link with the people of your choice."
  homepage "https://github.com/sesaamapp/sesaam-cli"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sesaamapp/sesaam-cli/releases/download/v0.3.0/sesaam_Darwin_x86_64.tar.gz"
      sha256 "55e5fb4be24a87ae046ba7a598507388c48f1de52b94dc9d4cfa2b587e02d2b0"

      def install
        bin.install "sesaam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sesaamapp/sesaam-cli/releases/download/v0.3.0/sesaam_Darwin_arm64.tar.gz"
      sha256 "072d8d9bb4c8c918952dddf982b707bca0b3afa30ce038c010ad3cfdae36e279"

      def install
        bin.install "sesaam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sesaamapp/sesaam-cli/releases/download/v0.3.0/sesaam_Linux_arm64.tar.gz"
      sha256 "04253f3f4f1e7889dbe4aa96e0cc44b2b9d7263730196aa75b9839bf57c89211"

      def install
        bin.install "sesaam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sesaamapp/sesaam-cli/releases/download/v0.3.0/sesaam_Linux_x86_64.tar.gz"
      sha256 "1949fb71066c104c5aa87fbbbba859d7ee0fe0bf5f9422f1621d36f838d2693b"

      def install
        bin.install "sesaam"
      end
    end
  end
end
